// GENERATED by build-from-brief.ts — do not edit by hand.
// Points each site image to a file whose extension matches its real format.
// This default references the template's placeholder assets; the builder
// overwrites it per client after downloading the pro's real photos.
import heroImg from "./hero.jpg";
import aboutImg from "./about.jpg";
import svc1Img from "./svc-1.jpg";
import svc2Img from "./svc-2.jpg";
import svc3Img from "./svc-3.jpg";
import flowerImg from "./flower.png";

export { heroImg, aboutImg, svc1Img, svc2Img, svc3Img, flowerImg };
